apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Release.Name }}-configmap
data:
  location: {{ .Values.location | lower | quote }}
  createdAt: {{ now | date "2020-01-01T10:20:30.000Z" | quote }}
  environmentName: {{ .Values.environmentName | default "dev" }}